# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6615b25ae162ab66f2938f2c6374f9f6841269e52d31ebbd6466f1f3ab6015c6aad9ba1b327b8b9ccaa4c45b455ca0405770cae7f2a2fe2866b59d7ba410843c

test:
  secret_key_base: 56cfa7312c52bc367b23f14f7351963351c6ccf229c1cdc97efc64b3234ab4b965ada0928020bd49692c3719c66b2011a6c76c5e50b6ab309648db51de0c264d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
